name: playground
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_mappr_annotation: ^2.2.0
  bloc: ^8.1.4
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  go_router: ^14.1.4
  injectable: ^2.4.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.11
  test: ^1.25.2
  json_serializable: ^6.8.0
  auto_mappr: ^2.5.0
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
